import { useContext, useState } from "react";
import Head from "next/head";
import Header from "./components/Header";
import MarkdownContainer from "./components/MarkdownContainer";
import MarkdownInput from "./components/MarkdownInput";
import MarkdownPreview from "./components/MarkdownPreview";
import { ThemeContext, MarkdownContext } from "../utils/contexts";

import { Inter } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  let themeContext = useContext(ThemeContext);
  let markdownContext = useContext(MarkdownContext);

  let [markdown, setMarkdown] = useState(markdownContext);
  let [theme, setTheme] = useState(themeContext);

  return (
    <>
      <Head>
        <title>Markdown-Html Previewer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <ThemeContext.Provider value={theme}>
          <Header
            onChangeTheme={(selectedTheme) =>
              setTheme({ default: selectedTheme })
            }
          />
          <MarkdownContainer>
            <MarkdownContext.Provider value={markdown}>
              <MarkdownInput
                onTransformMarkdown={(value) =>
                  setMarkdown({ htmlPreview: value.html })
                }
              />
              <MarkdownPreview />
            </MarkdownContext.Provider>
          </MarkdownContainer>
        </ThemeContext.Provider>
      </main>
    </>
  );
}
