import { useState } from "react";
import Head from "next/head";
import Header from "./components/Header";
import MarkdownContainer from "./components/MarkdownContainer";
import MarkdownInput from "./components/MarkdownInput";
import MarkdownPreview from "./components/MarkdownPreview";
import { ThemeContext, MarkdownContext } from "../Contexts";

import { Inter } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ["latin"] });

const markdownContextData = { htmlPreview: "" };

const themeContextData = {
  default: {
    name: "Mid Night",
    primaryColor: "#2c3e50",
    secondaryColor: "#34495e",
  },
};

export default function Home() {
  let [markdown, setMarkdown] = useState(markdownContextData);
  let [theme, setTheme] = useState(themeContextData);

  return (
    <>
      <Head>
        <title>Markdown-Html Previewer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <ThemeContext.Provider value={theme}>
          <Header
            onChangeTheme={(newTheme) => setTheme({ default: newTheme })}
          />
          <MarkdownContainer>
            <MarkdownContext.Provider value={markdown}>
              <MarkdownInput
                onTransformMarkdown={(value) =>
                  setMarkdown({ htmlPreview: value.html })
                }
              />
              <MarkdownPreview />
            </MarkdownContext.Provider>
          </MarkdownContainer>
        </ThemeContext.Provider>
      </main>
    </>
  );
}
